#!/usr/bin/env python3
from backbone.version_checker import VersionChecker
import argparse
import rospy
import rostopic


def main() -> int:
    rospy.init_node(name="version_checker", anonymous=True)
    parser = argparse.ArgumentParser(
        description="Checks the version of the messages sent to a topic"
    )
    parser.add_argument(
        "-t",
        "--topic",
        metavar="/topic",
        type=str,
        help="Topic to control",
        required=True,
    )
    parser.add_argument(
        "-m",
        "--message_type",
        metavar="std_msgs/String",
        type=str,
        help="Type of messages that gets published on target topic",
        required=False,
    )
    args = parser.parse_args()
    ver = rospy.get_param("version", None)
    field = rospy.get_param("VERSION_FIELD", None)
    if args.message_type:
        message_type = args.message_type
    else:
        message_type = rostopic.get_topic_type(args.topic, blocking=True)[0]
    if not ver or not field:
        raise ValueError(
            f"please remember to setup the version and VERSION_FIELD parameters on the master node "
        )
    else:
        checker = VersionChecker(args.topic, args.message_type)
        rospy.spin()
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
